# Generated by Django 5.1.4 on 2024-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la editorial')),
                ('country', models.CharField(max_length=50, verbose_name='País de origen')),
                ('founded_year', models.IntegerField(verbose_name='Año de fundación')),
            ],
        ),
    ]
